#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-forcats
Version  : 1.0.0
Release  : 53
URL      : https://cran.r-project.org/src/contrib/forcats_1.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/forcats_1.0.0.tar.gz
Summary  : Tools for Working with Categorical Variables (Factors)
Group    : Development/Tools
License  : MIT
Requires: R-cli
Requires: R-glue
Requires: R-lifecycle
Requires: R-magrittr
Requires: R-rlang
Requires: R-tibble
BuildRequires : R-cli
BuildRequires : R-glue
BuildRequires : R-lifecycle
BuildRequires : R-magrittr
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : buildreq-R

%description
Helpers for reordering factor levels (including moving specified levels to
front, ordering by first appearance, reversing, and randomly shuffling), and
tools for modifying factor levels (including collapsing rare levels into other,
'anonymising', and manually 'recoding').

%prep
%setup -q -n forcats
cd %{_builddir}/forcats

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678819807

%install
export SOURCE_DATE_EPOCH=1678819807
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/forcats/DESCRIPTION
/usr/lib64/R/library/forcats/INDEX
/usr/lib64/R/library/forcats/LICENSE
/usr/lib64/R/library/forcats/Meta/Rd.rds
/usr/lib64/R/library/forcats/Meta/data.rds
/usr/lib64/R/library/forcats/Meta/features.rds
/usr/lib64/R/library/forcats/Meta/hsearch.rds
/usr/lib64/R/library/forcats/Meta/links.rds
/usr/lib64/R/library/forcats/Meta/nsInfo.rds
/usr/lib64/R/library/forcats/Meta/package.rds
/usr/lib64/R/library/forcats/Meta/vignette.rds
/usr/lib64/R/library/forcats/NAMESPACE
/usr/lib64/R/library/forcats/NEWS.md
/usr/lib64/R/library/forcats/R/forcats
/usr/lib64/R/library/forcats/R/forcats.rdb
/usr/lib64/R/library/forcats/R/forcats.rdx
/usr/lib64/R/library/forcats/data/Rdata.rdb
/usr/lib64/R/library/forcats/data/Rdata.rds
/usr/lib64/R/library/forcats/data/Rdata.rdx
/usr/lib64/R/library/forcats/doc/forcats.R
/usr/lib64/R/library/forcats/doc/forcats.Rmd
/usr/lib64/R/library/forcats/doc/forcats.html
/usr/lib64/R/library/forcats/doc/index.html
/usr/lib64/R/library/forcats/help/AnIndex
/usr/lib64/R/library/forcats/help/aliases.rds
/usr/lib64/R/library/forcats/help/figures/README-ordered-plot-1.png
/usr/lib64/R/library/forcats/help/figures/README-unordered-plot-1.png
/usr/lib64/R/library/forcats/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/forcats/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/forcats/help/figures/logo.png
/usr/lib64/R/library/forcats/help/forcats.rdb
/usr/lib64/R/library/forcats/help/forcats.rdx
/usr/lib64/R/library/forcats/help/paths.rds
/usr/lib64/R/library/forcats/html/00Index.html
/usr/lib64/R/library/forcats/html/R.css
/usr/lib64/R/library/forcats/tests/testthat.R
/usr/lib64/R/library/forcats/tests/testthat/_snaps/anon.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/c.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/collapse.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/count.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/cross.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/drop.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/expand.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/explicit_na.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/fct.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/lump.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/lvls.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/match.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/na.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/other.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/recode.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/relabel.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/relevel.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/reorder.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/shift.md
/usr/lib64/R/library/forcats/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/forcats/tests/testthat/test-anon.R
/usr/lib64/R/library/forcats/tests/testthat/test-as_factor.R
/usr/lib64/R/library/forcats/tests/testthat/test-c.R
/usr/lib64/R/library/forcats/tests/testthat/test-collapse.R
/usr/lib64/R/library/forcats/tests/testthat/test-count.R
/usr/lib64/R/library/forcats/tests/testthat/test-cross.R
/usr/lib64/R/library/forcats/tests/testthat/test-drop.R
/usr/lib64/R/library/forcats/tests/testthat/test-expand.R
/usr/lib64/R/library/forcats/tests/testthat/test-explicit_na.R
/usr/lib64/R/library/forcats/tests/testthat/test-fct.R
/usr/lib64/R/library/forcats/tests/testthat/test-lump.R
/usr/lib64/R/library/forcats/tests/testthat/test-lvls.R
/usr/lib64/R/library/forcats/tests/testthat/test-match.R
/usr/lib64/R/library/forcats/tests/testthat/test-na.R
/usr/lib64/R/library/forcats/tests/testthat/test-other.R
/usr/lib64/R/library/forcats/tests/testthat/test-recode.R
/usr/lib64/R/library/forcats/tests/testthat/test-relabel.R
/usr/lib64/R/library/forcats/tests/testthat/test-relevel.R
/usr/lib64/R/library/forcats/tests/testthat/test-reorder.R
/usr/lib64/R/library/forcats/tests/testthat/test-rev.R
/usr/lib64/R/library/forcats/tests/testthat/test-shift.R
/usr/lib64/R/library/forcats/tests/testthat/test-shuffle.R
/usr/lib64/R/library/forcats/tests/testthat/test-unique.R
/usr/lib64/R/library/forcats/tests/testthat/test-utils.R
